apiVersion: v1
kind: ReplicaSet
metadata:
  name: my-new-rp
  labels:
    app: guestbook
    tier: frontend
spec:
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
    containers:
      - name: ny-new-app
        image: nginx
