nodes = [
  { :hostname => 'nfs-server',  :ip => '192.168.50.40', :ram => 1024, :box => 'generic/ubuntu2004', :forPort => 2103 }
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
	  nodeconfig.vm.network "forwarded_port",  guest: 22, host: node[:forPort]  ## in case you are in a vpn, you can redirect
	  #nodeconfig.vm.synced_folder "tmp/", "/tmp/cluster"  ## sync folders. useful when some nodes need other nodes info
      nodeconfig.vm.box = node[:box]  ## change name that appear in the virtual box
      nodeconfig.vm.hostname = node[:hostname] ## hostname of the vm
      nodeconfig.vm.network :private_network, ip: node[:ip]  ## configure network according to variables node
      nodeconfig.vm.provider :virtualbox do |domain|
        domain.memory = node[:ram] ## ram memory
        domain.cpus = 2 ## cpus
		domain.name = node[:hostname] ## change name that appear in ther virtual box
	  nodeconfig.vm.provision "main-scripts", :type => "shell", :path => "scripts/main-scripts.sh", :args => "#{node[:ip]}"  ## Execute base script
      end
    end
  end
end

