apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: finance
  name: {{ .Release.Name }}-finance-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: finance
status:
  loadBalancer: {}
