apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hr
  name: {{ .Release.Name }}-hr
spec:
  containers:
  - image: nginx
    name: hr
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: config-volume
    configMap: 
      name: {{ .Chart.Name }}-config-map
